name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - app/**
      - templates/**
      - .github/workflows/**
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t suchithra05/voting-app:latest .

    - name: Push to Docker Hub
      run: |
        docker push suchithra05/voting-app:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name demo-nodeport

    - name: Update image in Kubernetes
      run: |
        kubectl set image deployment/vote-deployment vote-app=suchithra05/voting-app:latest 
